### ISSUE TITLE
README.md 

### ISSUE THREAD

**Issue by doc-jones** [bloominstituteoftechnology/CS-Build-Week-1#209]
The second bullet in the **Stretch section**
inline link to 

> more deployment info here

The link is incorrect.  Change:
https://github.com/LambdaSchool/CS-Build-Week-1/blob/master/resources/deployment

to
[https://github.com/LambdaSchool/CS-Build-Week-1/tree/master/resources/web/deployment](https://github.com/LambdaSchool/CS-Build-Week-1/tree/master/resources/web/deployment)

**Comment by beejjorgensen** [comment]
Fixed.
