### ISSUE TITLE
All links on the visualization README.md

### ISSUE THREAD

**Issue by doc-jones** [bloominstituteoftechnology/CS-Build-Week-1#211]
Visualizations on this page

https://github.com/LambdaSchool/CS-Build-Week-1/tree/master/objectives/visualization

It appears that the correct link should be this one.

https://github.com/LambdaSchool/CS-Build-Week-1/tree/master/resources/web

**Comment by beejjorgensen** [comment]
Since the visualizations are track-specific, I just removed the link for now.
